### ISSUE TITLE
look into removing space from config/log paths

### ISSUE THREAD

**Issue by atinylittleshell** [atinylittleshell/TerminalOne#32]

**Comment by gplusplus314** [comment]
On this topic, using `~/.config/terminalone`, even on Windows, would be nice. It can be one of the directories it looks at. This is a nice-to-have for cross platform dotfiles.

**Comment by atinylittleshell** [comment]
@gplusplus314 check out https://github.com/atinylittleshell/TerminalOne/releases/tag/v1.6.0 and see #50 for details
