### ISSUE TITLE
acrylic setting does not work on MacOS / M1

### ISSUE THREAD

**Issue by sboesebeck** [atinylittleshell/TerminalOne#37]
setting of `acrylic: true` caueses the app to look like this on MacOS:

![image](https://github.com/atinylittleshell/TerminalOne/assets/1639447/9cb41138-6b41-4db3-a29d-a53b50ce4784)
![image](https://github.com/atinylittleshell/TerminalOne/assets/1639447/313fff5a-c85e-430a-83f4-d554bb17a230)

setting it to `false` shows proper behavior. There are no errors in the logs.
```
{"level":"info","message":"Loaded config from /Users/stephan/Library/Application Support/Terminal One/config.js}: {\"acrylic\":true}","timestamp":"2024-01-16 15:01:14.820"}
{"level":"info","message":"app started","timestamp":"2024-01-16 15:01:15.945"}
```

**Comment by sboesebeck** [comment]
my bad, config was wrong.

**Comment by atinylittleshell** [comment]
check this out - https://github.com/atinylittleshell/TerminalOne/releases/tag/v1.4.0 

we now release an arm64 build which might solve the problem here - let me know how it goes?

**Comment by atinylittleshell** [comment]
@sboesebeck @seasonedfish I just created an arm64 build for M1 in https://github.com/atinylittleshell/TerminalOne/releases/tag/v1.6.1. Do you mind trying it out and let me know if it works?

**Comment by atinylittleshell** [comment]
@seasonedfish @sboesebeck Do you mind trying  https://github.com/atinylittleshell/TerminalOne/releases/tag/v1.6.3 and see if the arm64 build helps address this problem?
