### ISSUE TITLE
[Bug] Tab does not close when shell terminates

### ISSUE THREAD

**Issue by gplusplus314** [atinylittleshell/TerminalOne#39]
When terminating a shell (for example, using the `exit` command), the tab remains open.

# Steps to reproduce:
1. Open a shell in TerminalOne.
2. Exit the shell via command line.
3. The shell process terminates.

## Actual:
The tab remains open.

## Expected:
The tab is destroyed. If it's the last tab, then the whole window should be destroyed.

# Environment:
OS: Windows 11 Pro, 23H2, 22631.3007
TerminalOne: rel v1.3.1

**Comment by atinylittleshell** [comment]
Good point - this should be straight forward. Will take a look to support.

**Comment by atinylittleshell** [comment]
@gplusplus314 check out https://github.com/atinylittleshell/TerminalOne/releases/tag/v1.5.0 :) it should be working according to your expected behavior now
