### ISSUE TITLE
Put the configuration in the .config folder

### ISSUE THREAD

**Issue by FormalSnake** [atinylittleshell/TerminalOne#44]

**Comment by atinylittleshell** [comment]
Agreed. This seems to be a common request, raised in https://github.com/atinylittleshell/TerminalOne/issues/32 as well. Will get to this soon

**Comment by atinylittleshell** [comment]
Consolidating this into #32

**Comment by atinylittleshell** [comment]
@FormalSnake this has been addressed. Check out https://github.com/atinylittleshell/TerminalOne/releases/tag/v1.6.0 and see #50 for details

**Comment by FormalSnake** [comment]
Nice!
