### ISSUE TITLE
javascript remarks

### ISSUE THREAD

**Issue by jerch** [atinylittleshell/TerminalOne#52]
xterm.js dev here - just saw your reddit post and ppl being concerned about performance with (yet another) JS driven terminal. 

Want to give you a few of my own impressions in that field (and since I dont have a reddit account I'll do it here, hope you dont mind):

As you already might have figured, xterm.js has taken some lengths to optimize execution performance (and still does, partially even with WASM drop-ins), be it for input processing, buffer handling or screen render performance (3 different renderers - sounds silly when just looking at this number). So whats the deal here?

Well since the invention of JIT and the constant improvements done to JIT engines like V8 Javascript isn't slow anymore per se - it is now more a mixed case ranging from 1,5 - 5x execution time for typical programming tasks. Where your very own code ends up in that range depends alot on how well you abide to assumption/pattern the JIT can easily optimize (to name a few we had to apply to xterm.js):
- many JS-ish pattern are still poison for the JIT (got somewhat better over time), so Javascript is its own enemy when it comes to perf requirements
- short functions / methods with stable type interfaces - any interface change or even accessing a value on an outer context might cause a bailout/de-opt in the JIT with bad perf again or the need to recompile
- sync vs async (eg. promises) - promises are way slower that plain sync code (async always involves some additional bookkeeping for the queue execution / stack reordering)
- the garbage collector is "garbage" for high perf needs - you will need object pooling/recycling or GC/allocation pressure will kill the fun
- perfwise JS strings are spoiled, they have seen some optimizations at various ends, that will bite you back at other ends, resort to typed arrays instead
- any data processing in JS is still worse than in high perf compiled languages even with typed arrays, prolly mainly due its deref needs when accessing values in container types (thats where even the JITed execution loses ground) - here WASM can bring you closer to C/C++ speed with 1-1.5x execution time

So when you read over the points above you might get the feeling whats going on - writing very C-ish code in Javascript/Typescript still gives you the fastest results before entering any WASM trickery. This is contradictory to what most webdevs learn these days, esp. regarding the GC (most ppl dont care for memory management at all anymore) with all the downsides - JS apps are perceived as fat and slow. And sadly thats true for most apps. But not because the language/engines cannot do any better - I tend to blame the devs, that dont learn anymore, how to write efficient code due to all the goodies the languages offers (which all come to a price). A quite infamous example is the runtime difference of a for-of-loop vs. a classical C-ish for-loop with index access.

**Comment by atinylittleshell** [comment]
@jerch thanks a lot for adding colors here! Great points and can't agree more. I still need to do a pass at profiling and removing  bottlenecks created by my code here. 

And kudos for the work on xterm.js - it's the GOAT! I was absolutely amazed how buttery smooth it is, especially seeing even some pure Rust implementations struggle to achieve the same.
